# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fe7d96847bf4ef2c12dd350250e782f8ae89c180c76770e90e136545f0e61407874c90fcc8a781a8f18256991f096eab0da2c67e93d47b7e13824d905160439a

test:
  secret_key_base: 98493efb4ee0bafba7932baaeb3b0a3d99e7ca9e82335b0d5580bb2e640199740182057debbaf51efbb46113e356258c6a3bab3ec4109ce18e54d793c7ea4470

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
