# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
c1 = Country.create(name: "Colombia", description: "Colombia es un país soberano situado en la región noroccidental de América del Sur. Está constituido en un estado unitario, social y democrático de derecho cuya forma de gobierno es presidencialista. Es una república que está organizada políticamente en 32 departamentos descentralizados y el Distrito capital de Bogotá, sede del gobierno nacional.11​", image: "https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=0ahUKEwip86K_mbTVAhXjy4MKHXm3BG8QjRwIBw&url=https%3A%2F%2Fcl.pinterest.com%2Fpin%2F155374255873767815%2F&psig=AFQjCNHqFr3HS4OwMYlX-s2VCsH169FitA&ust=1501613792599905")
c2 = Country.create(name: "Republica Dominicana", description: "República Dominicana es uno de los trece países que forman la América Insular, Antillas o Islas del mar Caribe, uno de los treinta y cinco del continente americano. Su capital y ciudad más poblada es Santo Domingo. Está ubicado en la zona central de las Antillas, en los dos tercios orientales de la isla La Española, limitando al norte con el océano Atlántico, al este con el Canal de la Mona, que lo separa de Puerto Rico, al sur con el mar Caribe, y al oeste con Haití, que es el otro país situado en La Española.", image: "https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=0ahUKEwjxwJScmrTVAhVM5YMKHbNlAMUQjRwIBw&url=https%3A%2F%2Fadompretur.org%2F&psig=AFQjCNEnQLApfRKcxWhimX6T8towm_016g&ust=1501613991979894")
Destination.create(name: "Punta Cana", description: "Punta Cana es una localidad situada al este de la República Dominicana, en la provincia de La Altagracia. En esta localidad se ubican varios complejos hoteleros, cuya superficie total es de unos 420 000 m² (equivalentes a 42 hectáreas o 0,42 km²).", image: "https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=0ahUKEwjL-dz3mrTVAhXC3YMKHc1mBHUQjRwIBw&url=http%3A%2F%2Fwww.godominicanrepublic.com%2Fes%2Fdestinos%2Fpuntacana-es%2F&psig=AFQjCNFfqmkTZn_ojFKmYZN21Gy23nKEkA&ust=1501614191822657", country_id: c2.id)
Destination.create(name: "Cartagena de Indias", description: "Cartagena de Indias, oficialmente Distrito Turístico y Cultural de Cartagena de Indias abreviado Cartagena de Indias, D. T. y C., es la capital del departamento de Bolívar, Colombia.6​ Fue fundada el 1.° de junio de 1533 por Pedro de Heredia.7​ Desde 1991 Cartagena es un Distrito Turístico y Cultural.8​ La ciudad está localizada a orillas del mar Caribe.", image: "https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=0ahUKEwjWoNjYm7TVAhXq7oMKHbGMD6oQjRwIBw&url=https%3A%2F%2Fwww.originaltravel.co.uk%2Fsouth-america%2Fcolombia%2Fcartagena&psig=AFQjCNFYtMnblPj-JaR3LaoBwhm-Fzk3-w&ust=1501614375543316", country_id: c1.id)
